// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffvajoxkxgzpqqdzdngp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmdmFqb3hreGd6cHFxZHpkbmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjQ5NTIsImV4cCI6MjA2NDI0MDk1Mn0.p_2OMPOBC-6DUeCwPYIRK47CZ5SyjZx04qZHICXjNkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);